### ISSUE TITLE
MantisBT 2.x compatibility

### ISSUE THREAD

**Issue by helfy022** [mantisbt-plugins/CustomizeEmailSubject#3]
Hello,

Eager to try out the CustomizeEmailSubject plug-in; however, the MantisCore requirement makes our current installation (2.5.1) ineligible:

$this->requires = array('MantisCore' => '1.2.14');

Does the plug-in need to be updated to be compatible with a MantisCore installation > 2.0.0?

Thanks,
Ryan.

**Comment by gaborgabor** [comment]
Any chance to get this updated to 2.x ?

**Comment by langerheiko** [comment]
Sorry, but I am not maintaining it, as my company is using Jira now...

Am 2. November 2018 14:24:30 MEZ schrieb Damien Regad <notifications@github.com>:
>@langerheiko are you still maintaining this plugin ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mantisbt-plugins/CustomizeEmailSubject/issues/3#issuecomment-435378988

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by dregad** [comment]
@langerheiko thanks for the feedback. 

Would you be so kind to 
- merge the changes from master branch in your original repository [CustomizeEmailSubject_for_MantisBT](https://github.com/langerheiko/CustomizeEmailSubject_for_MantisBT) into this repo (since they have diverged), 
- transfer ownership to the mantisbt-plugins org

Maybe someone will be interested to take maintenance over - if so, please ping @mantisbt-plugins/core-team.

**Comment by langerheiko** [comment]
Hi Damien,
I merged teh changes, but I cannot transfer the ownership. I get the error message: "mantisbt-plugins already has a repository in the langerheiko/CustomizeEmailSubject_for_MantisBT network". What am I doing wrong?
Best Regards
Heiko

**Comment by dregad** [comment]
@langerheiko fyi GitHub support have just made this repo the "main" one.

**Comment by Elompenta** [comment]
Still not working..
MantisBT Core 2.18.0 and the Plugin shows as mandatory "MantisBT Core 1.2.14" and there is no install button

**Comment by maturbet** [comment]
https://github.com/mantisbt-plugins/CustomizeEmailSubject/pull/6

**Comment by maturbet** [comment]
Hello @dregad 
Interested by my pull request ?
